name: Generate Snake Game

on:
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours
  workflow_dispatch:      # allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Use this Action
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ../../BeanPods/github-snake.svg
            ../../BeanPods/github-snake-dark.svg?palette=github-dark
            ../../BeanPods/github-snake.gif

